### ISSUE TITLE
Deleted servers are still visible, even though they should be deleted from database

### ISSUE THREAD

**Issue by notdesky** [Jovem-Blood/server-list#2]
When a server gets deleted, the expected behavior from the site is deleting the data on the database, so the server stops being shown. However, the actual behavior is that the site still shows the deleted server, resulting on a "ghost server".

**Comment by Jovem-Blood** [comment]
Well noted, I'll fix it on the next commits, Thanks!

**Comment by deeeesky** [comment]
Opening the issue again since the problem wasn't resolved yet, oopsie!
